### ISSUE TITLE
antiSMASH compatibility

### ISSUE THREAD

**Issue by lisizzz** [Finn-Lab/SanntiS#2]
I ran Sanntis with the --antismash_output option and created a JSON file successfully. But when I submitted the JSON file along with the input FASTA file to antiSMASH, I got the error below. I have also attached the JSON file below.

<img width="1149" alt="error" src="https://github.com/Finn-Lab/SanntiS/assets/118192474/690fed83-6c1b-41e8-973a-ea2a2160928c">

<img width="780" alt="json" src="https://github.com/Finn-Lab/SanntiS/assets/118192474/39d0bdb0-8b18-4175-b799-0f0839d936fd">

**Comment by SantiagoSanchezF** [comment]
Hello,

Thank you for bringing this to our attention

After reviewing the issue, it was found that there was a typo in the JSON keys and a variable type mismatch in the generated output. I've made the necessary amendments to the code, and we've pushed a new release with these fixes. You should be able to get the updated version from the repo or from bioconda once it's bumped.

To save you from rerunning the entire process, I've provided a Python script below that will correct the previously generated JSON files:

``` python
import sys
import json

def correct_json(input_file, output_file):
    with open(input_file, 'r') as h:
        data = json.load(h)
    
    # Correcting the variable type
    data['tool']['configuration']['greediness'] = str(data['tool']['configuration']['greediness'])

    for record in data['records']:
        for subregion in record['subregions']:
            # Fixing the typo 'deteils' -> 'details'
            if 'deteils' in subregion:
                subregion['details'] = subregion['deteils']
                del subregion['deteils']
    
    with open(output_file, "w") as h:
        json.dump(data, h, indent=4)

if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python script_name.py <input_file> <output_file>")
        sys.exit(1)

    input_file, output_file = sys.argv[1:3]
    correct_json(input_file, output_file)

```

Run the script by providing your old JSON file as input and specify where you'd like the corrected file to be saved.
Ensure you replace "script_name.py" with the actual name of the script if you decide to save it to a file.
```
python script_name.py old_file.json corrected_file.json
```

Thank you for your feedback
Best
Santiago
