### ISSUE TITLE
`sanntis --version` reports wrong version

### ISSUE THREAD

**Issue by jasmezz** [Finn-Lab/SanntiS#7]
The conda version of SanntiS 0.9.3.4 outputs the wrong version 0.9.3.3. See reproducible code example prompts and output below:

```
$ sanntis --version
SanntiS 0.9.3.3

$ conda list sanntis
# packages in environment at <path>/<to>/<conda>/sanntis:
#
# Name                    Version                   Build  Channel
sanntis                   0.9.3.4            pyhdfd78af_0    bioconda
```

**Comment by SantiagoSanchezF** [comment]
Hello,

Thank you for bringing this issue to our attention. The necessary corrections have been made.
Please allow some time for these updates to propagate. It will soon be reflected in the conda package.

If you encounter any further issues or have additional questions, feel free to reach out.

Best,
Santiago
